package graphics

import (
    "fmt"
)

// func Title () {
//     fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
//     fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _  ")
//     fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\ ")
//     fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |")
//     fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|")
//     fmt.Println("           oOO                                                                    OOo")
//     fmt.Println("         oOO                                                                        OOo")
//     fmt.Println("       oOO                                                                            OOo")
//     fmt.Println("      oOO                                                                              OOo")
//     fmt.Println("     oOO                                                                                OOo")
//     fmt.Println("    oOO                                                                                  OOo")
//     fmt.Println("   oOO                                                                                    OOo")
//     fmt.Println("  oOO                                                                                      OOo")
//     fmt.Println(" oOO                                                                                        OOo")
//     fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo")
//     fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo")
//     fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo")
//     fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo")
//     fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo")
//     fmt.Println(" oOO                                                                                        OOo")
//     fmt.Println("  oOO                                                                                      OOo")
//     fmt.Println("   oOO                                                                                    OOo")
//     fmt.Println("    oOO                                                                                  OOo")
//     fmt.Println("     oOO                                                                                OOo")
//     fmt.Println("      oOO                                                                              OOo")
//     fmt.Println("       oOO                                                                            OOo")
//     fmt.Println("         oOO                                                                        OOo")
//     fmt.Println("           oOO                                                                    OOo")
//     fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _  ")
//     fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\ ")
//     fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |")
//     fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|")
//     fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
// }

func Printer (question string, a string, b string, c string, d string, i int) {
    printPrize()
    fmt.Println("<<  " + question + "  >>")
    fmt.Println("< (a) " + a + " >" + "       " + "< (b) " + b + " >")
    fmt.Println("< (c) " + c + " >" + "       " + "< (d) " + d + " >")
}


func printPrize() {
    fmt.Println("                                                                                                +-----------------------+")
    fmt.Println("                                                                                                |          £1,000,000   |")
    fmt.Println("                                                                                                +-----------------------+")
    fmt.Println("                                                                                                  +---------------------+")
    fmt.Println("                                                                                                  |          £500,000   |")
    fmt.Println("                                                                                                  +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |   £1000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £200   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £100   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |**** £0 **|")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
