package graphics

import (
    "fmt"
)

func Printer (question string, a string, b string, c string, d string, i int) {
    printPrize(i)
    fmt.Println("<<  " + question + "  >>")
    fmt.Println("< (a) " + a + " >" + "       " + "< (b) " + b + " >")
    fmt.Println("< (c) " + c + " >" + "       " + "< (d) " + d + " >")
}

func printPrize(i int) {
    switch i {
    case 0: prize0()
    case 1: prize1()
    case 2: prize2()
    case 3: prize3()
    case 4: prize4()
    case 5: prize5()
    case 6: prize6()
    case 7: prize7()
    case 8: prize8()
    case 9: prize9()
    case 10: prize10()
    case 11: prize11()
    case 12: prize12()
    case 13: prize13()
    case 14: prize14()
    case 15: prize15()
    }
}



func prize0() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize1() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |** £100 **|")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize2() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |** £200 **|")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize3() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |** £300 **|")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize4() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |** £500 **|")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize5() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |* £1,000 *|")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize6() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |** £2,000 **|")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize7() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |** £4,000 **|")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize8() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |** £8,000 **|")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize9() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |* £16,000 **|")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize10() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |* £32,000 **|")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize11() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |*** £64,000 **|")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize12() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |**** £125,000 **|")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize13() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |****** £250,000 **|")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize14() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |          £1,000,000   |")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |********* £500,000 **|")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |   £200   |")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
func prize15() {
    fmt.Println("               INSTRUCTIONS                                                                     +-----------------------+")
    fmt.Println("       Select answer -> a, b, c, d                                                              |********* £1,000,000 **|")
    fmt.Println("      Take the money -> t                                                                       +-----------------------+")
    fmt.Println("               50:50 -> 1                                                                         +---------------------+")
    fmt.Println("       Call a friend -> 2                                                                         |          £500,000   |")
    fmt.Println("    Ask the audience -> 3                                                                         +---------------------+")
    fmt.Println("                     oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo                           +------------------+")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                  |       £250,000   |")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                 +------------------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                  +----------------+")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                  |     £125,000   |")
    fmt.Println("           oOO                                                                    OOo                  +----------------+")
    fmt.Println("         oOO                                                                        OOo                  +--------------+")
    fmt.Println("       oOO                                                                            OOo                |    £64,000   |")
    fmt.Println("      oOO                                                                              OOo               +--------------+")
    fmt.Println("     oOO                                                                                OOo                +------------+")
    fmt.Println("    oOO                                                                                  OOo               |  £32,000   |")
    fmt.Println("   oOO                                                                                    OOo              +------------+")
    fmt.Println("  oOO                                                                                      OOo             |  £16,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println(" oO ███    ███  ██  ██       ██       ██   ██████   ███    ██   █████   ██  ██████   ███████ Oo            |   £8,000   |")
    fmt.Println(" oO ████  ████  ██  ██       ██       ██  ██    ██  ████   ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██ ████ ██  ██  ██       ██       ██  ██    ██  ██ ██  ██  ███████  ██  ██████   █████   Oo            |   £4,000   |")
    fmt.Println(" oO ██  ██  ██  ██  ██       ██       ██  ██    ██  ██  ██ ██  ██   ██  ██  ██  ██   ██      Oo            +------------+")
    fmt.Println(" oO ██      ██  ██  ███████  ███████  ██   ██████   ██   ████  ██   ██  ██  ██   ██  ███████ Oo            |   £2,000   |")
    fmt.Println(" oOO                                                                                        OOo            +------------+")
    fmt.Println("  oOO                                                                                      OOo               +----------+")
    fmt.Println("   oOO                                                                                    OOo                |  £1,000  |")
    fmt.Println("    oOO                                                                                  OOo                 +----------+")
    fmt.Println("     oOO                                                                                OOo                  |   £500   |")
    fmt.Println("      oOO                                                                              OOo                   +----------+")
    fmt.Println("       oOO                                                                            OOo                    |   £300   |")
    fmt.Println("         oOO                                                                        OOo                      +----------+")
    fmt.Println("           oOO                                                                    OOo                        |** £200 **|")
    fmt.Println("             _ _ _  _ _   _    _ _ _   _   _  _  ___  __   ___   _    ___  ___    _                          +----------+")
    fmt.Println("            | | | || U | / \\  | | | | / \\ | \\| ||_ _|/ _| |_ _| / \\  | o )| __|  / \\                         +----------+")
    fmt.Println("            | V V ||   |( o ) | V V || o || \\\\ | | | \\_ \\  | | ( o ) | o \\| _|  | o |                        |   £100   |")
    fmt.Println("             \\_n_/ |_n_| \\_/   \\_n_/ |_n_||_|\\_| |_| |__/  |_|  \\_/  |___/|___| |_n_|                        +----------+")
    fmt.Println("                        oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo")
}
